
services:
  v1:
    build: ./app/v1
    ports:
      - "3001:3001"

  v2:
    build: ./app/v2
    ports:
      - "3002:3002"

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    environment:
      PORT: 80
      V1_HOSTPORT: v1:3001
      V2_HOSTPORT: v2:3002
    depends_on:
      - v1
      - v2
